### ISSUE TITLE
Input in navbar should disable "enter" downKey

### ISSUE THREAD

**Issue by santaclauze** [yeutech-lab/rollup-umd-documentation#46]
Description in title.

It reloads the page when pressing enter in sidebar menu search input.
Must be disabled

**Comment by kopax** [comment]
This is not an issue. 

This is due to the fact that the input button is in a form.
Default `type` for button is `submit`.

Changing to `<button type="button" />` would solve the submission issue.

Also, submitting of form can be disabled, for example

```jsx
function onClick(event) {
  event.preventDefault()
}
```
